// <auto-generated />
namespace Sadna_17_B.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class j : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(j));
        
        string IMigrationMetadata.Id
        {
            get { return "202407141715446_j"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
